[metadata]
category = "azl-pruning"
upstream-status = "inapplicable"
[[overlays]]
description = "Remove recommends: default-yama-scope"
type = "spec-search-replace"
regex = "^Recommends: default-yama-scope$"
replacement = ""
